### ISSUE TITLE
Field type for foreign key

### ISSUE THREAD

**Issue by krawalli** [quietcreep/meteor-formation#11]
for a foreign key to another Model/Collection simply use the .Char type or is there already some magic implemented?

**Comment by quietcreep** [comment]
Already magic. For foreign key type relationships, use the ModelSingleChoice field.  So like this.

```javascript
field = new Fields.ModelSingleChoice({ model: myRelatedModel })
```

For M2M relationships use:
```javascript
field = new Fields.ModelMultipleChoice({ model: myRelatedModel })
```
