### ISSUE TITLE
idea: unique field value

### ISSUE THREAD

**Issue by krawalli** [quietcreep/meteor-formation#12]
a unique check for validation if field value is unique in collection(filter)

**Comment by quietcreep** [comment]
There is a unique field param, but I'm not sure if it's working. If you've got a project, try putting ```unique: true``` into your field param. It may or may not work at the moment, but there is beginning support for it.

**Comment by quietcreep** [comment]
I'm closing this for now. Reopen it if you bump up against any issues with the current "unique".
