### ISSUE TITLE
feature: i18n or user defined validator messages

### ISSUE THREAD

**Issue by krawalli** [quietcreep/meteor-formation#15]
For i18n or user defined (validation) messages. there should be a Settings Object for all Models.

**Comment by quietcreep** [comment]
There is a Formation.Settings object, but as of now, there's nothing really in it. What would be in the Settings?

I've been meaning to move all the error messages to a consolidated object.  Maybe they can go in Settings.Errors? That way if a user wants to overwrite or translate errors messages, they can do so. 

For i18n, I think that should be divided out into packages for specific languages, like formation-i18n-fr or formation-i18n-en. That way on load it would automatically replace what's in Settings.Errors.

What do you think?

**Comment by krawalli** [comment]
for i18n i would wait until a official package / solution is done. 
Till then, make them over-writable by settings would be more than enough. Maybe the text could be a String or a Function. With second all existing i18n packages could be used by user.

Maybe
~~~js
Formation.Settings.set('msg', 'validator_number', {nan: 'this is not a number, dude!"});
~~~

**Comment by quietcreep** [comment]
See what you think of this commit.

Btw, are you using the GitHub repo, or the Atmosphere package?

**Comment by krawalli** [comment]
I forked the repos and use the local version of the packages.

**Comment by quietcreep** [comment]
Ok, then I won't worry about publishing until things are settled.
