### ISSUE TITLE
Number Validator wont give message for "not a number"

### ISSUE THREAD

**Issue by krawalli** [quietcreep/meteor-formation#17]
test with: "3s" -> no message shown.

In validator the *value* is 0 (instead of 3s), so the check(value, Number) will always let it pass and wont trigger the message "Please enter a number value."

PS: sorry for spamming issues ;)

**Comment by quietcreep** [comment]
Found out that the + type coercion turns '3s' into NaN, which passes check for Number. I'm now having the fromDOM method return undefined if NaN, and checking for NaN in the validator.

Reopen if anything else pops up.
