### ISSUE TITLE
code style

### ISSUE THREAD

**Issue by krawalli** [quietcreep/meteor-formation#18]
Would you mind to get closer to: 
https://github.com/meteor/meteor/wiki/Meteor-Style-Guide

on source code style?

My current editor (sublime) is equipped with a plugin that would take care of most of those rules.

I've seem some files with <tab>, some with <space>.

To get closer on onw formatting base would make it easier to create pull requests.

**Comment by quietcreep** [comment]
For now, I'm going to call this a wontfix. I've adhered to the styles that I find easiest to read, and made exceptions where it's harder to read for me.

Do your plugins only operate on the whole document, or do they enforce rules as you type?

**Comment by krawalli** [comment]
Whole document.
