### ISSUE TITLE
customize instanceSummary

### ISSUE THREAD

**Issue by krawalli** [quietcreep/meteor-formation#21]
Is there a setting for customizing *instanceSummary*?

Background:
I have some boolean fields and instead of plain true/false text i want to show some fancy stuff. Can i hook some template into that like the *repr* or *toString*?

**Comment by quietcreep** [comment]
For a model?  When you define a model, you can include a summary function.

```javascript
myModel = Model({
  schema: {...},
  summary: function(){
    var politeBool = this.bool.value ? "Yes, ma'am" : "No, ma'am";
    return this.name.value + ': ' + politeBool;
  }
})
```

You can also customize a template
```Handlebars
<template name="customBool">
  {{# if inEditMode }}
    {{> dxInput bool }}
  {{ else }}
    <span class="display-mode">
      {{# if bool.value }}
        Yes, ma'am.
      {{ else }}
        No, ma'am.
      {{/ if }}
    </span>
  {{/ if }}
</template>
````

**Comment by krawalli** [comment]
dxField returns just that instanceSummary toDOM or how could that template be specified?

**Comment by quietcreep** [comment]
I've always hated that instanceSummary helper.

I removed it, and in its place added a ```summary``` param to every field to be called in the template. Now when you define a field, you can add a summary function that returns what you want it to return.

**Comment by krawalli** [comment]
so summary is more like repr in python?

**Comment by quietcreep** [comment]
I'd say it's more similar to javascript's toString. Most JS objects have a toString method.
