### ISSUE TITLE
interrupt save method

### ISSUE THREAD

**Issue by illmat** [quietcreep/meteor-formation#22]
I'm trying to use a model with the Meteor.users collection.
Therefore I need a custom save method to call Accounts.createUser().
Either you could make the beforeSave interrupts the save method by returning false or you could let us define a custom save method.
The only way I could make this work is by throwing an error in the beforeSave event.

**Comment by quietcreep** [comment]
So you're using the ModelInstance to handle display and data collection, but you don't need the built in save method?

I think the best way to do this would be something like this:

Create a user Model with no collection that matches the signature of Accounts.createUser:
```javascript
var Users = Model({
  schema: {
    username: new Fields.Char({ max: 255, unique: true }),
    email: new Fields.Email({ max: 255 }),
    profile: Model({ schema: {
      firstName: new Fields.Char({ max: 255 }),
      lastName: new Fields.Char({ max: 255 }),
      //...
    }})
  },
});
```

Then something like
```Handlebars
<template name="newUserForm">
  {{# with newUser }}
    {{> dxField username }}
    {{> dxField username }}
    {{> dxField profile.firstName }}
    {{> dxField profile.lastName }}
    <button class="btn btn-primary btn-lg" data-action="save-user">save new user</button>
  {{/ with }}
</template>
```

Then in the template js file
```javascript
Template.newUserForm.helpers({
  newUser: function(){ return new Users.newInstance };
})

Template.newUserForm.events({
  'click [data-action=save]': function( event ){
    event.preventDefault();
    Accounts.createUser( this.getValue() );
    // do other things here
  }
})
```

**Comment by quietcreep** [comment]
Also this just gave me an idea; how about accepting a custom save method for Models with no collection?  Would that be something you'd use?

**Comment by krawalli** [comment]
At least I would :)

**Comment by illmat** [comment]
Sounds promising.

**Comment by quietcreep** [comment]
@illmat done. Try it out and let me know if there are any issues.

You can now add a custom save function to a Model with no collection. So, something like this:

```javascript
var Users = Model({
  schema: {
    username: new Fields.Char({ max: 255, unique: true }),
    email: new Fields.Email({ max: 255 }),
    profile: Model({ schema: {
      firstName: new Fields.Char({ max: 255 }),
      lastName: new Fields.Char({ max: 255 }),
      //...
    }})
  },
  save: function(){
    Accounts.createUser( this.getValue() );
  }),
});
```

should do what you want.

**Comment by krawalli** [comment]
nice!

You should consider about re-naming the package to somethink like clever-models :)

**Comment by illmat** [comment]
I really appreciate your quick response times. 
I'll give it a try tomorrow.
Wouldn't it be nice to have the option for a custom save function even while using a collection?
