### ISSUE TITLE
field type for array (of Strings)

### ISSUE THREAD

**Issue by krawalli** [quietcreep/meteor-formation#24]
What is the desired field type for an array of e.g. String?

.Fields.MultipleChoice
seems to be the choice but after validate the array value is gone (create a model with newInstance works). But since validate does not like it, nothing inside the Array is saved.

**Comment by quietcreep** [comment]
Can you show me what you're doing. Not sure I see what's happening.

**Comment by krawalli** [comment]
I want to create newInstances of a model because of an import of data. So i create a JSON object with the data.
After that i create the model with
~~~ javascript
note = new Notes.newInstance(rawnote);
~~~
rawnote is the json and note is the created model.

The schema of Notes consists of:
~~~javascript
    contacts: new Formation.Fields.MultipleChoice({
      choices: function () {
        //return Contacts.findOne({'_id': this.value}, {fields: {'_id': 1}});
        return [this.value];
      }
    }),
~~~~
Contacts is a collection not turned into model yet. However it could be an array of strings for some other use cases. I tried some code (as seen above) to trick the validate.

on start validate the content.value is { value: [ 'FjqHDfpXkhKBkWzYJ' ] }
but turns now somewhere in code to { value: [ ] }
The empty array is saved, but thats not what I want ;)

I think the main problem is that I inject the data from code, not from DOM.
Also there are so many possibilities but I cannot give the "choices" a (regex) pattern what to accept.

**Comment by krawalli** [comment]
And I did another approach with:
~~~javascript
    contacts: [new Fields.Char({
      max: 20,
      required: false
    })],
~~~

but that causes a little exception:
TypeError: undefined is not a function
    at ModelInstance.initArray (packages/quietcreep:formation-core/models/modelInstanceSuper.js:368:1)
    at ModelInstance._traverseModel (packages/quietcreep:formation-core/models/modelInstanceSuper.js:342:1)

From the example inside an array should be another model. but however a simple Sting would be enough.

**Comment by quietcreep** [comment]
Alright, last question until I finish the README.  

If you're looking to store an array of _id references to models, you should use ModelMultipleChoice:
```javascript
contacts: new Fields.ModelMultipleChoice({ model: Contacts })
```

If you're looking to store an array of arbitrary strings, you should use CharArray.  An array of numbers you'd use NumberArray.

**Comment by krawalli** [comment]
CharArray? Too simple :D

Not listed (yet) in the Type list (what an excuse!).

Thank you for your patience and sorry for my lame questions. It's working!
