### ISSUE TITLE
Accessing _id in afterSave method

### ISSUE THREAD

**Issue by illmat** [quietcreep/meteor-formation#26]
Is there a way to acces the _id of a freshly saved data record inside the afterSave method?
I'm try to store a reference to this data record in another Collection.

**Comment by illmat** [comment]
I've created a PR for the core package which should fix this issue.

**Comment by quietcreep** [comment]
Let me know if the PR fixed everything. I'm in the middle of another project at the moment, but I'll check it out when I get a chance.
