### ISSUE TITLE
Update package.js to use formation-core 2.0.7 instead of 2.0.6

### ISSUE THREAD

**Issue by illmat** [quietcreep/meteor-formation#28]
The actual package.js says:
```
api.use([ 'quietcreep:formation-core@2.0.6', ...
```
formation-core@2.0.7 is what we want ;)

Thanks

**Comment by quietcreep** [comment]
Thanks for the heads up! I didn't catch this. All updated / published.

Also, you've been pretty involved; would you like to be a contributor?

**Comment by illmat** [comment]
Yeah, would be great. There are various things in my mind which I want to improve if I find the time.
