### ISSUE TITLE
Revert any changes when clicking cancel

### ISSUE THREAD

**Issue by rvanhoepen** [quietcreep/meteor-formation#4]
When a user edits a field and clicks cancel, the modified value is displayed.
In almost every case this would be undesirable behaviour.

If a user edits his/her profile and click cancel and see the updated values being 
displayed they will assume that the values was saved to the DB.

**Comment by quietcreep** [comment]
Huh, I didn't think anyone was using this but me. I've been meaning to fix this for some time, but it hadn't yet been a breaking issue in any of my projects.

I just began replacing the stock insert, update, and remove calls with custom Meteor.methods for more sophisticated handling of nested models, and I should be able to use something like the new ones to revert on cancel. Although if you have any other suggestions, I'd be happy to hear them.

I'll take a look at this ASAP.

**Comment by rvanhoepen** [comment]
+1 for the quick response. I actually found this project on Atmosphere and it solved a problem I was
still trying to implement on my own. Will definitely make other suggestions as soon as I see another
need.

I wanted to just fix the issue on my own and make a pull request, but I don't have time to look
through all the subprojects at this stage.

**Comment by quietcreep** [comment]
Try this most recent update.  If you're handling saving/canceling manually, just call .revert() on a ModelInstance to revert it to the most recent saved version.  I don't know how well this will work; there are a couple of edge cases that I have my suspicions about...

I'll close for now, but reopen if something pops up.

**Comment by quietcreep** [comment]
Oh, also, what problem were you trying to work around on your own? 

I wrote this because I came from Django and was looking for a solution more like that for form/model handling, specifically one with references to other data models and nested data structures.
