### ISSUE TITLE
idea: layout

### ISSUE THREAD

**Issue by krawalli** [quietcreep/meteor-formation#9]
What about adding a property where you can define the desired layout to prevent recurring definition of 
~~~html
....
 {{> dxField username}}
      {{> dxField emails.[0].address}}
      {{> dxField profile.first_name}}
      {{> dxField profile.last_name}}
      {{> dxButtons}}
~~~

Example:
~~~js
MyModel = new Model({
  schema: {
     field1: ....
     field2: ....
     field3: ....
     field4: ....
  virtualFields: ....
  layout: [
   'field3',
  'field1',
  'field2'
  ]
});
~~~

Now you could use {{#each layout}} {{> dxField this}}  (and maybe a default helper for that e.g. {{> dxDoLayout}}) as a one line in your template. This could result in consistent display of the form if used in more than one place.

**Comment by quietcreep** [comment]
I recently got done adding support for an "attributes" argument to a model.

If you'd like to turn off the built-in bootstrap support you can do something like this:
```javascript
Categories = Model({
  collection: new Mongo.Collection( 'categories' ), 
  schema: {
    name: new Formation.Fields.Char({ max: 255 }),
    ...
  },
  attributes: {
    bootstrap: false,
    class: 'some-custom-class',
    data-action: 'submit',
  },
  ...
})
```
You can do this per model (to apply the same attributes to each field) and/or per field for more granular styling control.

Finally, there's a nice little template helper that you can use to do styling in the template rather than in the model / field definition if you like.

```Handlebars
<form>
  {{# with userForm }}
    {{> dxField setAttributes context=username class="borderless-field" bootstrap=false }}
  {{/ with }}
</form>
```

And, yes, I know a README will help, but it also takes a little bit to put together.

**Comment by quietcreep** [comment]
Also, I generally like the layout idea, but I've tried to keep the styling and data logic somewhat separate. Seems like a more Meteor-ish approach would just be to add form templates for reuse.

I could see about doing a quick form approach where one helper like ```{{> dxForm myModel }}``` renders all editable/savable fields.  Would that be something you're interested in?

**Comment by krawalli** [comment]
hehe, just start with the README - there will be some Pull-Request :)

However, I got not the individual styling of a input in mind. My thought was to predefine the order of the fields to show in a form, so for the most simple use case all you need to say in a template is *"print the form for the model right here - done"*

**Comment by quietcreep** [comment]
I'll close for now, but I am interested in doing a {{ >dxForm }} type helper. It's not really something that comes up too ofter for me, so if you'd like to take a stab at it, please do.
